language: python
python:
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_script:
  - pip install -r test_requirements.txt
script:
  - "coverage run --source eynnyd/ -m unittest discover tests/"
after_success:
  - coveralls
